services:
- type: worker
name: watch-bot
runtime: python
plan: starter
buildCommand: pip install -r requirements.txt && python -m playwright install --with-deps
startCommand: python app.py
envVars:
- key: 8392040450:AAHFEHMA2TIwvKtp3FUPJ1oeI_HMT-TDfMM
s
